export const GETALLUSERLIST = "GETALLUSERLIST";
export const GETALLUSERLISTSUCCESS = "GETALLUSERLISTSUCCESS";
export const ISUSERDETAILSMODALOPEN = "ISUSERDETAILSMODALOPEN";
export const CLOSEUSERDETAILSMODAL = "CLOSEUSERDETAILSMODAL";