export const GETALLUSERLIST = "GETALLUSERLIST";
export const GETALLUSERLISTSUCCESS = "GETALLUSERLISTSUCCESS";
export const ISUSERDETAILSMODALOPEN = "ISUSERDETAILSMODALOPEN";
export const CLOSEUSERDETAILSMODAL = "CLOSEUSERDETAILSMODAL";
export const DELETEUSER = "DELETEUSER";
export const OPENUSERDELETEMODAL = "OPENUSERDELETEMODAL";
export const CLOSEUSERDELETEMODAL = "CLOSEUSERDELETEMODAL";
export const AFTERSEARCHUSERSLIST = "AFTERSEARCHUSERSLIST";
export const OPENADDNEWUSERMODAL = "OPENADDNEWUSERMODAL";
export const CLOSEADDNEWUSERMODAL = "CLOSEADDNEWUSERMODAL";

export const OPENUPDATEUSERMODAL = "OPENUPDATEUSERMODAL";
export const CLOSEUPDATEUSERMODAL = "CLOSEUPDATEUSERMODAL";

export const ISINFINITELOADER = "ISINFINITELOADER";
export const ISUSERLOADER = "ISUSERLOADER";
export const ISBOTTOM = "ISBOTTOM";

export const USERDETAILSINITIATE = 'USERDETAILSINITIATE'
export const USERDETAILSSUCCESS = 'USERDETAILSSUCCESS'
export const USERDETAILSFAILURE = 'USERDETAILSFAILURE'

export const SEARCHINPUTS = 'SEARCHINPUTS'

export const ADDNEWUSER = 'ADDNEWUSER'
